plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
	id 'me.modmuss50.mod-publish-plugin' version "$mod_publish_version"
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

repositories {
	// Add repositories to retrieve artifacts from in here.
	// You should only use this when depending on other mods because
	// Loom adds the essential maven repositories to download Minecraft and libraries from automatically.
	// See https://docs.gradle.org/current/userguide/declaring_repositories.html
	// for more information about repositories.
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"

	localRuntime "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
}

loom {
    accessWidenerPath = file("src/main/resources/${archives_base_name}.classTweaker")

    runs {
        client {
            client()
            setConfigName('Fabric Client')
            ideConfigGenerated(true)
            runDir('run/client')
        }
        server {
            server()
            setConfigName("Fabric Server")
            ideConfigGenerated(true)
            runDir('run/server')
        }
    }
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": inputs.properties.version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = java_version.toInteger()
}

java {
	toolchain.languageVersion = JavaLanguageVersion.of(java_version)

	withSourcesJar()
}

jar {
	inputs.property "archivesName", project.base.archivesName

	from("LICENSE") {
		rename { "${it}_${inputs.properties.archivesName}"}
	}
}

publishMods {
	dryRun = false
	version = this.version
	type = STABLE
	changelog = file('CHANGELOG.md').text
	file = jar.archiveFile
	additionalFiles.from(sourcesJar.archiveFile)

	github {
		accessToken = findProperty("GITHUB_TOKEN") ?: ''
		repository = "fishstiz/soft-loader"
		commitish = "26.1"
		tagName = "v${mod_version}"
		displayName = "v${mod_version}"
	}

	modrinth {
		accessToken = findProperty("MODRINTH_TOKEN") ?: ''
		projectId = modrinth_id
		modLoaders.add("fabric")
		minecraftVersions.addAll(minecraft_version)
	}

	curseforge {
		accessToken = findProperty("CURSEFORGE_TOKEN") ?: ''
		projectId = curseforge_id
		modLoaders.add("fabric")
		minecraftVersions.addAll("26.1-snapshot")
		clientRequired = true
	}
}