# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

java_version=25

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1-rc-3
loader_version=0.18.4
loom_version=1.15-SNAPSHOT

# Mod Properties
mod_version=1.0.0+26.1
maven_group=io.github.fishstiz.soft_loader
archives_base_name=soft_loader
modrinth_id=5rm8pdXm
curseforge_id=1339769

# Dependencies
fabric_version=0.144.0+26.1
mod_publish_version=0.8.4